services:
  runner:
    build: .
    privileged: true
    hostname: docker-composite-runner-1
    volumes:
      - runner-data:/actions-runner/data
      - type: bind
        source: .env
        target: /actions-runner/.env
        read_only: true
    restart: always

  runner-2:
    hostname: docker-composite-runner-2
    extends: runner

  runner-3:
    hostname: docker-composite-runner-3
    extends: runner

volumes:
  runner-data:
